### ISSUE TITLE
Lists screen

### ISSUE THREAD

**Issue by ElNgatia** [JaxiroKe/SonglibApp#3]
Number of songs in a list updates after closing the app or when a new list is created

**Comment by ElNgatia** [comment]
https://user-images.githubusercontent.com/72346625/231879017-270e5759-b0c6-420f-bd30-0e54c07a91c1.mp4

Here's a video. The number of songs in a list will update after the app is closed or a new list is created

**Comment by Oyonde** [comment]
Okay will work on this soon, thanks for the heads up
